include(FeatureDetection/FeatureDetection.pri)
include(DTO/DTO.pri)
include(Image/Image.pri)
include(FeatureMatching/FeatureMatching.pri)
include(FeatureTracking/FeatureTracking.pri)
include(DescriptorExtractor/DescriptorExtractor.pri)
